name: PR

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  # Ensure single build of a pull request. `main` should not be affected.
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-commit:
    name: "lint PR title"
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      # We lint the PR title instead of the commit message to avoid script injection attacks.
      # Using environment variables prevents potential security vulnerabilities as described in:
      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack
      - name: Lint PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" | npx @rnx-kit/commitlint-lite@2.0.0
  build-website:
    name: "Build the website"
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install package dependencies
        run: |
          yarn
      - name: Build website
        run: |
          yarn build

