name: PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

