name: PR

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  # Ensure single build of a pull request. `main` should not be affected.
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-commit:
    name: "lint commit message"
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Lint commit message
        run: |
          yarn lint:commit
  build-website:
    name: "Build the website"
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install package dependencies
        run: |
          yarn
      - name: Build website
        run: |
          yarn build

